# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spree-order-comments}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gary Taylor"]
  s.date = %q{2011-02-03}
  s.email = %q{gary.taylor@rubysystems.co.uk}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "app/controllers/comments_controller.rb",
     "app/models/comment.rb",
     "app/views/admin/orders/_tab.html.erb",
     "app/views/admin/orders/comments.html.erb",
     "config/locales/en-US.yml",
     "config/routes.rb",
     "lib/spree_order_comments.rb",
     "lib/spree_order_comments_hooks.rb",
     "lib/tasks/install.rake",
     "lib/tasks/order_comments_extension_tasks.rake"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Gemified version of spree-order-comments}
  s.test_files = [
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<acts_as_commentable>, [">= 0"])
    else
      s.add_dependency(%q<acts_as_commentable>, [">= 0"])
    end
  else
    s.add_dependency(%q<acts_as_commentable>, [">= 0"])
  end
end

